/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_NativeProcessor */

#ifndef _Included_com_example_NativeProcessor
#define _Included_com_example_NativeProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_NativeProcessor
 * Method:    calculateAverage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_NativeProcessor_calculateAverage
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     com_example_NativeProcessor
 * Method:    calculateMax
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_NativeProcessor_calculateMax
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     com_example_NativeProcessor
 * Method:    countUnique
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_NativeProcessor_countUnique
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
