/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_NativeProcessor */

#ifndef _Included_com_example_NativeProcessor
#define _Included_com_example_NativeProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_NativeProcessor
 * Method:    initNativeLib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_NativeProcessor_initNativeLib
  (JNIEnv *, jclass);

/*
 * Class:     com_example_NativeProcessor
 * Method:    calcAverage
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_NativeProcessor_calcAverage
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     com_example_NativeProcessor
 * Method:    calcMax
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_NativeProcessor_calcMax
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     com_example_NativeProcessor
 * Method:    countUnique
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_NativeProcessor_countUnique
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
