/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Main */

#ifndef _Included_com_example_Main
#define _Included_com_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Main
 * Method:    initNativeLib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_Main_initNativeLib
  (JNIEnv *, jclass);

/*
 * Class:     com_example_Main
 * Method:    calcAverage
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_Main_calcAverage
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     com_example_Main
 * Method:    calcMax
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_Main_calcMax
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     com_example_Main
 * Method:    countUnique
 * Signature: ([DI)I
 */
JNIEXPORT jint JNICALL Java_com_example_Main_countUnique
  (JNIEnv *, jclass, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
